### PR TITLE
added localization of the table "locales_creature"

### PR DESCRIPTION
**Pull request by schnek**
image

### CODE REVIEW

**Comment by Appled** [comment]
I think these should be pushed to AscEmu base repository instead

**Comment by Zyres** [comment]
Interesting: are locales part of the normal db updates or is it more a feature provided by us?
If it is a part required to be updated for everyone it should be created on AscEmu/AscEmu

**Comment by schnek** [comment]
these are regional features. (TimeZone)
I use TimeZone   = "12" what gives me Cyrillic instead of Latin...

```

> #    TimeZone:
> #        The location of the server.
> #        0 = Korean 10 = French 21 = CN5
> #        1 = Development 11 = Spanish 22 = CN6
> #        2 = United States 12 = Russian 23 = CN7
> #        3 = Oceanic 13 = Tournament 24 = CN8
> #        4 = Latin America 14 = Taiwan 25 = Tournament
> #        5 = Tournament 15 = Tournament 26 = Test Server
> #        6 = Korean 16 = China 27 = Tournament
> #        8 = English 17 = CN1 28 = QA Server
> #        9 = German 18 = CN2 29 = CN9
> #        10 = French 19 = CN3 30 = TestServer2
> #        20 = CN4
> 
```

**Comment by schnek** [comment]
> If it is a part required to be updated for everyone it should be created on AscEmu/AscEmu

yes you can transfer. ideally, you can add an auto setting of the locale for a specific language via cmake))

**Comment by Appled** [comment]
> 
> 
> Interesting: are locales part of the normal db updates or is it more a feature provided by us?
> If it is a part required to be updated for everyone it should be created on AscEmu/AscEmu

Yeah they are part of normal db updates. I think TC has recently been updating locales.
So technically if you have a chinese client, you should see quests and items in chinese. Here's a nice preview of it https://www.youtube.com/watch?v=Mmx3v0UAclg

**Comment by schnek** [comment]
yes in ascent there was a function that, when using a Chinese client, added the ability to use a Cyrillic.

 `<Localization LocaleBindings="enGB=ruRU">`

**Comment by Zyres** [comment]
Okay, so @schnek make a PR on AscEmu/AscEmu :-)

**Pull request closed without merging**
